Fix body too big when we get metadata, create multiple query, one per…
rewiko/curator pull request #1
Opened 2018-01-16 11:23 UTC by rewiko

Fixes Avoid querying all the indices in on go, the payload is too big depending on the number of indeces and the elasticsearch configuration. (specially on AWS when you can't customize the payload parameter) - getting HTTP/1.1 413 FULL head when you have too much indices.

## Proposed Changes

  - Making a request per index to get information

2018-02-09 16:25 UTC, MalsR requested changes
Would be good to have some tests around it but I know it can be tough in this case...

2018-02-09 16:25 UTC, MalsR commented on curator/indexlist.py
> +    def get_indices_stats(self, data):
Since `get_indices_stats`, `bulk_queries` and `get_cluster_state` are all private methods they should contain the leading underscore that declares them private methods? (I'm not a python expert :) )

2018-02-09 16:25 UTC, MalsR commented on curator/indexlist.py
> +    def get_indices_segments(self, data):
private method

2018-02-09 16:25 UTC, MalsR commented on curator/indexlist.py
> +    def get_cluster_state(self, data):
This method is referenced by two other private methods; I think `_get_metadata` is fine but `_get_index_stats` used  to filter by the following metrics 
`metric='store,docs'`
instead of
`metric='metadata'` is that ok? I think you might need to change it to be ``metric='store,docs'`` similar to `_get_segmentcounts`

2018-02-09 16:25 UTC, MalsR commented on curator/indexlist.py
>      def _get_segmentcounts(self):
Should it be `_get_segment_counts`

2018-02-09 16:25 UTC, MalsR commented on curator/indexlist.py
> +        return self.client.cluster.state(index=to_csv(data),metric='metadata')['metadata']['indices']
I'm nitpicking space after comma `,metric='metadata'`

2018-02-12 10:24 UTC, rewiko commented on curator/indexlist.py
> +    def get_indices_stats(self, data):
done

2018-02-12 10:24 UTC, rewiko commented on curator/indexlist.py
> +    def get_indices_segments(self, data):
done

2018-02-12 10:25 UTC, rewiko commented on curator/indexlist.py
>      def _get_segmentcounts(self):
done

2018-02-12 10:28 UTC, rewiko commented on curator/indexlist.py
> +    def get_cluster_state(self, data):
I don't see your point, I didn't change the query it was like that.

2018-02-12 10:29 UTC, rewiko commented on curator/indexlist.py
> +        return self.client.cluster.state(index=to_csv(data),metric='metadata')['metadata']['indices']
done

2018-02-12 10:30 UTC, rewiko commented on curator/indexlist.py
>      def _get_segmentcounts(self):
done

2018-02-12 11:11 UTC, rewiko commented
Ready to review again

2018-02-12 11:11 UTC, rewiko commented
Ready to review again

2018-02-23 14:02 UTC, merged